### ISSUE TITLE
How add thumbail image post

### ISSUE THREAD

**Issue by Ivantiger** [Vimux/Amnix#1]
Hello!

Please help, How add thumbail image post Amnix theme (example Mainroad theme).

I to insert thumbnail: "img/placeholder.jpg" md file, not working...

**Comment by Vimux** [comment]
First of all, it's WIP. I don't recommend to use this theme. Here be dragons and some other weird stuff.

Second, [README#featured-images](https://github.com/Vimux/Amnix#featured-images) and [exampleSite folder](https://github.com/Vimux/Amnix/tree/master/exampleSite/content) could helps.
