### ISSUE TITLE
Ft. Req: Make feature image optional in single.html

### ISSUE THREAD

**Issue by karlredman** [Vimux/Amnix#2]
Hi, I love your theme.

I would like to add a config parameter and/or front matter parameter that will *not* show a featured image on the post page. I have working code for a config parameter now but can add a front matter condition easily.

Would you like a pull request for this feature? And if so, what would you like to call the parameter(s)? 

Otherwise I would love to have this functionality without forking.

The change wold look something like this in `layouts/_default/single.html:

```
{{- if or (.Site.Params.pagefeatured) (.Params.pagefeatured) }}
    {{- partial "post/post_featured.html" (dict "page" . ) }}
{{end}}
```

**Comment by Vimux** [comment]
Hi, @karlredman

> I would like to add a config parameter and/or front matter parameter that will not show a featured image on the post page.

I have nothing against this change at the WIP stage. Of course, this should be work in both cases (as site config param & frontmatter param).

> And if so, what would you like to call the parameter(s)?

I don’t like the current proposal name (`pagefeatured`). You need to use something else, more meaningful... `hideSingleFeatured`?

>```
> {{- if or (.Site.Params.pagefeatured) (.Params.pagefeatured) }}
>    {{- partial "post/post_featured.html" (dict "page" . ) }}
> {{end}}
> ```

Why not [.Param](https://gohugo.io/functions/param/)? Am I missing something?
